[package]
name = "crisp-zk-inputs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core logic to pre-compute CRISP ZK inputs (WASM/JavaScript bindings)."

[lib]
crate-type = ["cdylib"]

[dependencies]
zk-inputs = { path = "../zk-inputs" }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.2"
