[package]
name = "crisp_circuit"
type = "bin"
version = "0.1.0"
authors = ["Gnosis Guild / Enclave"]
license = "MIT"

[dependencies]
greco = { path = "../../../circuits/crates/libs/greco" }
polynomial = { path = "../../../circuits/crates/libs/polynomial" }
safe = { path = "../../../circuits/crates/libs/safe" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
binary_merkle_root = { git = "https://github.com/zk-kit/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }