[package]
name = "keyshare"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
data = { path = "../data" }
cipher = { path = "../cipher" }
config = { path = "../config" }
enclave-core = { path = "../core" }
fhe = { path = "../fhe" }
serde = { workspace = true }
tracing = { workspace = true }
