[package]
name = "crisp-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
e3-sdk = { workspace = true, default-features = false, features=["bfv"] }
eyre = { workspace = true }
hex = { workspace = true }
num-bigint = "=0.4.6"

