[package]
name = "parity-matrix"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Parity Matrix for the linear subspace of Z_q^{n+1}"
repository = "https://github.com/gnosisguild/enclave/crates/parity_matrix"

[dependencies]
num-bigint = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }

[[bin]]
name = "parity-matrix"
path = "src/bin/parity_matrix.rs"