[package]
name = "aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
config = { path = "../config" }
async-trait = { workspace = true }
enclave-core = { path = "../core" }
fhe = { path = "../fhe" }
sortition = { path = "../sortition" }
data = { path = "../data" }
tracing = { workspace = true }
