[package]
name = "evm"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = { workspace = true }
alloy = { workspace = true }
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
cipher = { path = "../cipher" }
config = { path = "../config" }
data = { path = "../data" }
events = { workspace = true }
futures-util = { workspace = true }
sortition = { path = "../sortition" }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
enclave_core = { workspace = true }

