[package]
name = "evm"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = { workspace = true }
alloy = { workspace = true }
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
enclave-core = { path = "../core" }
data = { path = "../data" }
futures-util = { workspace = true }
sortition = { path = "../sortition" }
tokio = { workspace = true }
tracing = { workspace = true }
