[package]
name = "parity-matrix"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Parity Matrix for the linear subspace of Z_q^{n+1}"
repository = "https://github.com/gnosisguild/enclave/crates/parity-matrix"

[dependencies]
num-bigint = { workspace = true, features = ["serde"] }
num-traits = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }