[package]
name = "e3-user-program"
version = "0.1.0"
edition = "2024"

[dependencies]
fhe = { workspace = true }
fhe-traits = { workspace = true }
e3-compute-provider = { workspace = true }
e3-bfv-helpers = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
anyhow = { workspace = true }
