[package]
name = "e3-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "E3 - Enclave SDK"
repository = "https://github.com/gnosisguild/enclave/crates/sdk"

[dependencies]
e3-evm-helpers = { workspace = true, optional = true }
e3-bfv-client = { workspace = true, optional = true }
e3-fhe-params = { workspace = true, optional = true }
e3-indexer = { workspace = true, optional = true }

[features]
default = ["full"]
full = ["evm", "bfv", "indexer"]
indexer = ["dep:e3-indexer"]
evm = ["dep:e3-evm-helpers"]
bfv = ["dep:e3-bfv-client", "dep:e3-fhe-params"]
