[package]
name = "evm-helpers"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CRISP EVM Contract Helpers"

[dependencies]
alloy.workspace = true
eyre.workspace = true

[dev-dependencies]
tokio.workspace = true
alloy = { workspace = true, features = ["node-bindings"] }

