[workspace]
resolver = "3"
members = [
  "program",
  ".enclave/support/dev"
]

[workspace.dependencies]
e3-user-program = { path = "./program" }
fhe = { package = "fhe", git = "https://github.com/gnosisguild/fhe.rs" }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs" }
e3-program-server = { path = "../../crates/program-server" }
e3-bfv-helpers = { path = "../../crates/bfv-helpers" }
e3-compute-provider = { path = "../../crates/compute-provider" }
rand = "0.8.5"
anyhow = "1.0.86"
