chains:
  - name: "localhost"
    rpc_url: "ws://localhost:8545"
    contracts:
      enclave:
        address: "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e"
        deploy_block: 19
      ciphernode_registry:
        address: "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"
        deploy_block: 17
      bonding_registry:
        address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853"
        deploy_block: 14
      fee_token:
        address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
        deploy_block: 10
      e3_program:
        address: "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E"
        deploy_block: 32
program:
  dev: true
nodes:
  cn1:
    address: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    quic_port: 9201
    autonetkey: true
    autopassword: true
  cn2:
    address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    quic_port: 9202
    autonetkey: true
    autopassword: true
  cn3:
    address: "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
    quic_port: 9203
    autonetkey: true
    autopassword: true
  cn4:
    address: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
    quic_port: 9204
    autonetkey: true
    autopassword: true
  cn5:
    address: "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
    quic_port: 9205
    autonetkey: true
    autopassword: true
  ag:
    address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    quic_port: 9206
    autonetkey: true
    autopassword: true
    role:
      type: "aggregator"

