[package]
name = "e3-safe"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "E3 - Enclave SAFE"
repository = "https://github.com/gnosisguild/enclave/crates/safe"

[dependencies]
sha3 = "0.10.8"
ark-ff = { workspace = true }
ark-bn254 = { workspace = true }
taceo-poseidon2 = { version = "0.2", features = ["bn254", "t4"] }
hex = { workspace = true }
