[package]
name = "fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
config = { path = "../config" }
data = { path = "../data" }
enclave-core = { path = "../core" }
fhe-traits = { workspace = true }
fhe-util = { workspace = true }
fhe_rs = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
