[package]
name = "e3-zk-helpers"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ZK circuit helpers"
repository = "https://github.com/gnosisguild/enclave/crates/zk-helpers"

[dependencies]
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
e3-polynomial = { workspace = true }
e3-safe = { workspace = true }
fhe = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }

[[bin]]
name = "zk_cli"
path = "src/bin/zk_cli.rs"