[package]
name = "e3-zk-helpers"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ZK circuit helpers"
repository = "https://github.com/gnosisguild/enclave/crates/zk-helpers"

[dependencies]
anyhow = { workspace = true }
ark-bn254 = { workspace = true }
clap = { workspace = true }
ark-ff = { workspace = true }
e3-polynomial = { workspace = true, features = ["serde"] }
e3-safe = { workspace = true }
e3-fhe-params = { workspace = true }
fhe = { workspace = true }
fhe-math = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8.23"
itertools = "0.14.0"

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "zk_cli"
path = "src/bin/zk_cli.rs"