[package]
name = "e3-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository = "https://github.com/gnosisguild/enclave/crates/sync"

[dependencies]
actix.workspace = true
e3-events.workspace = true
