[package]
name = "e3-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository = "https://github.com/gnosisguild/enclave/crates/sync"

[dependencies]
actix.workspace = true
anyhow.workspace = true
e3-events.workspace = true
e3-data.workspace = true
e3-config.workspace = true
e3-utils.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
e3-events = { workspace = true, features = ["test-helpers"] }
e3-ciphernode-builder.workspace = true
e3-test-helpers.workspace = true
