[package]
name = "enclave"
version = "0.1.0"
edition = "2021"
description = ": coordinates the encryption and decryption of enclave computations"
repository = "https://github.com/gnosisguild/enclave/packages/ciphernode"

[dependencies]
actix = { workspace = true }
anyhow = { workspace = true }
cipher = { path = "../cipher" }
clap = { workspace = true }
compile-time = { workspace = true }
config = { path = "../config" }
dialoguer = "0.11.0"
enclave-core = { path = "../core" }
runtime = { workspace = true }
hex = { workspace = true }
petname = "2.0.2"
rand = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true } 
zeroize = { workspace = true }

