[package]
name = "enclave"
version = "0.1.0"
edition = "2021"
description = ": coordinates the encryption and decryption of enclave computations"
repository = "https://github.com/gnosisguild/enclave/packages/ciphernode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { workspace = true }
alloy = { workspace = true }
anyhow = { workspace = true }
cipher = { path = "../cipher" }
clap = { workspace = true }
config = { path = "../config" }
data = { path = "../data" }
dialoguer = "0.11.0"
enclave-core = { path = "../core" }
evm = { path = "../evm" }
enclave_node = { path = "../enclave_node" }
hex = { workspace = true }
once_cell = "1.20.2"
router = { path = "../router" }
rpassword = "7.3.1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true } 
zeroize = { workspace = true }
