node:
  address: "${ADDRESS}"
  quic_port: ${QUIC_PORT}
  peers:
    - "/dns4/cn1/udp/9091/quic-v1"
    - "/dns4/cn3/udp/9093/quic-v1"
    - "/dns4/aggregator/udp/9094/quic-v1"
chains:
  - name: "sepolia"
    rpc_url: "${RPC_URL}"
    contracts:
      enclave: "${SEPOLIA_ENCLAVE_ADDRESS}"
      ciphernode_registry: "${SEPOLIA_CIPHERNODE_REGISTRY_ADDRESS}"
      filter_registry: "${SEPOLIA_FILTER_REGISTRY}"
