[profile.mainnet] 
# RISC Zero Verifier contract deployed on mainnet (see https://dev.risczero.com/api/blockchain-integration/contracts/verifier#deployed-verifiers)
chainId = 1
riscZeroVerifierAddress = "0x8EaB2D97Dfce405A1692a21b3ff3A172d593D319"
enclaveAddress = "0xE3000000000000000000000000000000000000E3"
inputValidatorAddress = "0x0000000000000000000000000000000000000000"

[profile.sepolia]
# RISC Zero Verifier contract deployed on sepolia (see https://dev.risczero.com/api/blockchain-integration/contracts/verifier#deployed-verifiers)
chainId = 11155111
riscZeroVerifierAddress = "0x925d8331ddc0a1F0d96E68CF073DFE1d92b69187"
enclaveAddress = "0xE3000000000000000000000000000000000000E3"
inputValidatorAddress = "0x0000000000000000000000000000000000000000"

# You can add additional profiles here
[profile.custom]
chainId = 31337
riscZeroVerifierAddress = "0x0000000000000000000000000000000000000000" # Deployed with the script. Don't set or it will be skipped.
enclaveAddress = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0" # Based on default deployment address using local anvil node
inputValidatorAddress = "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853" # Based on default deployment address using local anvil node
