[workspace]
members = [
  "server",
  ".enclave/support/dev",
  "program",
  "crates/zk-inputs",
  "crates/zk-inputs-wasm"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-only"
description = "CRISP â€” Voting Application on Enclave"
repository = "https://github.com/gnosisguild/enclave"

[workspace.dependencies]
e3-user-program = { path = "./program" }

alloy-primitives = { version = "=1.3.0", default-features = false, features = [
    "rlp",
    "serde",
    "std",
]}
alloy-sol-types = { version = "=1.3.0" }
anyhow = { version = "=1.0.98" }
actix-web = "=4.11.0"
bincode = { version = "=1.3.3" }
bytemuck = { version = "=1.23.1" }
derivative = "=2.2.0"
e3-compute-provider = { path = "../../crates/compute-provider" }
e3-program-server = { path = "../../crates/program-server" }
e3-bfv-helpers = { path = "../../crates/bfv-helpers" }
e3-sdk = { path = "../../crates/sdk", default-features = false }
eyre = "=0.6.12"
env_logger = "=0.11.8"
hex = { version = "=0.4.3" }
log = { version = "=0.4.27" }
reqwest = { version = "=0.12.22", features = ["json"] }
serde = { version = "=1.0.228", features = ["derive", "std"] }
serde_json = "=1.0.141"
fhe = { git = "https://github.com/gnosisguild/fhe.rs" }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs" }
fhe-math = { git = "https://github.com/gnosisguild/fhe.rs.git" }
fhe-util = { git = "https://github.com/gnosisguild/fhe.rs" }
tokio = { version = "=1.46.1", features = ["full"] }
rand = { version = "=0.8.5" }
tracing-subscriber = { version = "=0.3.19", features = ["env-filter"] }
