[workspace]
members = [
    "pk_generation",
    "pk_aggregation",
    "user_data_encryption_ct0",
    "user_data_encryption_ct1",
    "share_decryption",
    "decrypted_shares_aggregation_bn",
    "decrypted_shares_aggregation_mod"  
    
]