[package]
name = "e3-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
actix.workspace = true
alloy.workspace = true
anyhow.workspace = true
derivative.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
