[package]
name = "e3-pvss"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PVSS core codegen and computation crate"
repository = "https://github.com/gnosisguild/enclave/crates/pvss"
 
[dependencies]
e3-polynomial = { workspace = true }
fhe = { workspace = true }
fhe-math = { workspace = true }
e3-fhe-params = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
itertools = "0.14.0"
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8.23"
anyhow = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
