[package]
# we have to name this other than core for disambiguation
name = "enclave-core"
version = "0.1.0"
edition = "2021"
description = ": coordinates the encryption and decryption of enclave computations"
repository = "https://github.com/gnosisguild/enclave/packages/ciphernode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
libp2p = "0.53.2"
fhe = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
fhe-util = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
actix = "0.13.5"
actix-rt = "2.10.0"
anyhow = "1.0.86"
rand = "0.8.5"
rand_chacha = "0.3.1"
secp256k1 = "0.29.0"
tokio = { version = "1.39.3", features = ["full"] }
sha2 = "0.10.8"
bs58 = "0.5.1"
serde = { version = "1.0.208", features = ["derive"] }
bincode = "1.3.3"
futures-util = "0.3"
alloy = { version = "0.3.3", features = ["full"] }
alloy-primitives = { version = "0.6", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.6" }
base64 = "0.22.1"
base91 = "0.1.0"
