[package]
name = "user_data_encryption"
type = "bin"
authors = ["Gnosis Guild / Enclave"]

[dependencies]
lib = { path = "../../../../../lib" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20260102", directory = "barretenberg/noir/bb_proof_verification" }
