[workspace]
members = [
    "fold",
    "insecure/pk_trbfv_wrapper",
    "insecure/verify_shares_trbfv_wrapper",
    "insecure/enc_bfv_wrapper",
    "insecure/dec_bfv_wrapper",
    "insecure/pk_agg_trbfv_wrapper",
    "insecure/dec_share_trbfv_wrapper",
    "insecure/dec_shares_agg_trbfv_wrapper",
    "insecure/pk_trbfv_wrapper",
    "production/verify_shares_trbfv_wrapper",
    "production/enc_bfv_wrapper",
    "production/dec_bfv_wrapper",
    "production/pk_agg_trbfv_wrapper",
    "production/dec_share_trbfv_wrapper",
    "production/dec_shares_agg_trbfv_wrapper"
]