[package]
name = "crisp_fold"
type = "bin"
version = "0.1.0"
authors = ["Gnosis Guild / Enclave"]

[dependencies]
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20260102", directory = "barretenberg/noir/bb_proof_verification" }
