[package]
name = "sortition"
version = "0.1.0"
edition = "2021"
description = ": coordinates the encryption and decryption of enclave computations"
repository = "https://github.com/gnosisguild/enclave/packages/ciphernode"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { workspace = true }
alloy = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
async-trait = { workspace = true }
data = { path = "../data" }
enclave-core = { path = "../core" }
num = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
