[package]
name = "zk-inputs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core logic to pre-compute CRISP ZK inputs."

[dependencies]
e3-sdk = { workspace = true, default-features = false, features=["bfv"] }
fhe.workspace = true
fhe-math.workspace = true
fhe-traits.workspace = true
e3-bfv-client = { workspace = true }
e3-fhe-params = { workspace = true }
greco = { package = "zkfhe-greco", git = "https://github.com/gnosisguild/zkfhe-generator" }
e3-zk-helpers = { workspace = true }
e3-polynomial = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
num-bigint = "0.4.6"
num-traits = "0.2"
rayon = "1.10.0"
rand = "0.8.5"
hex = "0.4.3"
itertools = "0.14.0"
eyre.workspace = true
ark-bn254 = "0.5"
ark-ff = "0.5"



