[package]
name = "enclave_core"
version = "0.1.0"
edition = "2021"
description = ": coordinates the encryption and decryption of enclave computations"
repository = "https://github.com/gnosisguild/enclave/packages/ciphernode"
build = "build.rs"

[dependencies]
actix = { workspace = true }
aggregator = { workspace = true }
alloy = { workspace = true }
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
config = { workspace = true }
clap = { workspace = true }
crypto = { workspace = true }
data = { workspace = true }
dirs = { workspace = true }
events = { workspace = true }
evm = { workspace = true }
fhe = { workspace = true }
hex = { workspace = true }
keyshare = { workspace = true }
logger = { workspace = true }
libp2p = { workspace = true }
net = { workspace = true }
phf = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
e3_request = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sortition = { workspace = true }
test-helpers = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }
actix-web = { workspace = true }
reqwest = { workspace = true }

[build-dependencies]
serde_json = { workspace = true }
