[package]
name = "e3-user-program"
version = "0.1.0"
edition = "2024"

[dependencies]
fhe = { workspace = true }
fhe-traits = { workspace = true }
e3-compute-provider = { git = "https://github.com/gnosisguild/enclave", rev = "632766e4ed1ceeccdeb023a56f16413a33be6f46" }
e3-bfv-helpers = { git = "https://github.com/gnosisguild/enclave", rev = "632766e4ed1ceeccdeb023a56f16413a33be6f46" }
