[package]
name = "e3-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
e3-bfv-helpers.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.99"
