[package]
# we have to name this other than core for disambiguation
name = "events"
version = "0.1.0"
edition = "2021"
description = ": coordinates the encryption and decryption of enclave computations"
repository = "https://github.com/gnosisguild/enclave/packages/ciphernode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { workspace = true }
sha2 = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
futures-util = { workspace = true }
alloy = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }
